import type { Metadata } from "next";
// import WagmiConfigProvider from "@/context/wagmiProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import PrivyProviderWrapper from "@/context/PrivyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <WagmiConfigProvider>
          {children}
        </WagmiConfigProvider> */}
        <PrivyProviderWrapper>
          {children}
        </PrivyProviderWrapper>
      </body>
    </html>
  );
}
